intrinsics:
  camera_matrix:
  - 376.6869473024056
  - 0.0
  - 318.1658197521198
  - 0.0
  - 376.67926795109804
  - 247.68392644478962
  - 0.0
  - 0.0
  - 1.0
  dist_coeffs:
  - -0.007359038257331093
  - -0.10004233758035878
  - -0.00230046817365035
  - -0.0008217400189285176
  - 0.3129295580544872
  image_size:
  - 640
  - 480
  reprojection_error: 0.0
extrinsics:
  rvec:
  - 2.1481470990703064
  - -0.04375212680837324
  - 0.021126407866517916
  tvec:
  - 0.27095121829271773
  - 0.0413414638738932
  - 1.2604590296920843
  T_cam_robot:
  - 0.9992094092852452
  - -0.03971285195713343
  - -0.0018562826461435535
  - 0.27095121829271773
  - -0.023241727262135525
  - -0.5456251706662302
  - -0.8377069865109874
  - 0.0413414638738932
  - 0.03225489900316038
  - 0.8370878463607496
  - -0.5461167997465539
  - 1.2604590296920843
  - 0.0
  - 0.0
  - 0.0
  - 1.0
