object_detection_node:
  ros__parameters:
    camera_calibration_file: ''
    color_topic: /camera/camera/color/image_raw
    depth_topic: /camera/camera/aligned_depth_to_color/image_raw
    camera_info_topic: /camera/camera/color/camera_info
    detector_type: color
    hsv_low:
    - 143
    - 106
    - 96
    hsv_high:
    - 179
    - 255
    - 229
    bgr_low:
    - 0
    - 0
    - 0
    bgr_high:
    - 255
    - 255
    - 255
    crop:
    - 0
    - 0
    - 640
    - 480
    min_area: 100
    label: object
    depth_range:
    - 0.1
    - 2.0
    depth_patch_radius: 3
    publish_rate: 30.0
    object_offset_robot:
    - 0.01
    - 0.02
    - 0.0
